name: 'Lint Code'
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Linter
        run: |
          # This finds all Python files recursively and runs flake8
          find . -name "*.py" -exec flake8 {} +
          echo "Python linting completed"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Recommended: latest LTS

      - name: Install JSHint
        run: npm install jshint --global

      - name: Run Linter
        run: |
          # Finds all JS files recursively (frontend & Node backend)
          find ./ -name "*.js" -exec jshint {} +
          echo "JavaScript linting completed"
